[package]
name = "plotters-gtk-demo"
version = "0.1.0"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "0.15.11"
gtk = "0.15.5"
gio = "0.15.11"

[dependencies.plotters]
git = "https://github.com/plotters-rs/plotters"
default_features = false
features = ["surface_series"]

[dependencies.plotters-cairo]
git = "https://github.com/plotters-rs/plotters-cairo"
